{
 "title": "ALEO SNARKOS MINER",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Handshakes Init Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_handshakes_successes_init", "legendFormat": "SUCCESS INIT" },
    { "expr": "aleo_handshakes_failures_init", "legendFormat": "FAILURE INIT" }
   ]
  },
  {
   "title": "Connections Acceptance Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_connections_all_accepted", "legendFormat": "success" },
    { "expr": "aleo_connections_all_rejected", "legendFormat": "rejected" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aleo_node_currently_connected_peers",
     "legendFormat": " peers connected:"
    }
   ]
  },
  {
   "title": "Local Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "aleo_misc_block_height", "legendFormat": "block:" }
   ]
  },
  {
   "title": "Local Height",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_misc_block_height", "legendFormat": " " }
   ]
  },
  {
   "title": "MINED BLOCKS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_misc_blocks_mined", "legendFormat": " " }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aleo_node_currently_connected_peers",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{job=\"aleo-server-exporter\"} * 100) / node_memory_MemTotal_bytes{job=\"aleo-server-exporter\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_nodeinfo_is_miner", "legendFormat": "MINER STATUS" },
    { "expr": "aleo_nodeinfo_is_syncing", "legendFormat": "OUT OF SYNC" }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"aleo-server-exporter\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{job=\"aleo-server-exporter\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{job=\"aleo-server-exporter\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"aleo-server-exporter\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"aleo-server-exporter\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{job=\"aleo-server-exporter\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',job=\"aleo-server-exporter\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{job=\"aleo-server-exporter\"}) by (cpu))"
    }
   ]
  },
  { "title": "handshakes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Successes RESP",
   "type": "stat",
   "description": "Handshakes Successes RESP",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_successes_resp", "legendFormat": " " }
   ]
  },
  {
   "title": "Success INIT",
   "type": "stat",
   "description": "Handshakes",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_successes_init", "legendFormat": " " }
   ]
  },
  {
   "title": "Timeouts INIT",
   "type": "stat",
   "description": "Handshakes timeouts INIT",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_timeouts_init", "legendFormat": " " }
   ]
  },
  {
   "title": "Failures RESP",
   "type": "stat",
   "description": "Handshakes",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_failures_resp", "legendFormat": " " }
   ]
  },
  {
   "title": "Failures INIT",
   "type": "stat",
   "description": "Handshakes",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_failures_init", "legendFormat": " " }
   ]
  },
  {
   "title": "Timeouts RESP",
   "type": "stat",
   "description": "Handshakes Timeouts RESP",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_handshakes_timeouts_resp", "legendFormat": " " }
   ]
  },
  { "title": "Inbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "blocks",
   "type": "stat",
   "description": "Inbound blocks",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_blocks", "legendFormat": " " }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "description": "Inbound transactions",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_transactions", "legendFormat": " " }
   ]
  },
  {
   "title": "all successes",
   "type": "stat",
   "description": "Inbound all successes",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_all_successes", "legendFormat": " " }
   ]
  },
  {
   "title": "getblocks",
   "type": "stat",
   "description": "Inbound getblocks",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_getblocks", "legendFormat": " " }
   ]
  },
  {
   "title": "pongs",
   "type": "stat",
   "description": "Inbound pongs",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_pongs", "legendFormat": " " }
   ]
  },
  {
   "title": "syncblocks",
   "type": "stat",
   "description": "Inbound syncblocks",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_syncblocks", "legendFormat": " " }
   ]
  },
  {
   "title": "getsync",
   "type": "stat",
   "description": "Inbound getsync",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_getsync", "legendFormat": " " }
   ]
  },
  {
   "title": "peers",
   "type": "stat",
   "description": "Inbound peers",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_peers", "legendFormat": " " }
   ]
  },
  {
   "title": "memorypool",
   "type": "stat",
   "description": "Inbound memorypool",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_memorypool", "legendFormat": " " }
   ]
  },
  {
   "title": "getpeers",
   "type": "stat",
   "description": "Inbound getpeers",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_getpeers", "legendFormat": " " }
   ]
  },
  {
   "title": "getmemorypool",
   "type": "stat",
   "description": "Inbound getmemorypool",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_getmemorypool", "legendFormat": " " }
   ]
  },
  {
   "title": "pings",
   "type": "stat",
   "description": "Inbound pings",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_pings", "legendFormat": " " }
   ]
  },
  {
   "title": "syncs",
   "type": "stat",
   "description": "Inbound syncs",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_syncs", "legendFormat": " " }
   ]
  },
  {
   "title": "all failures",
   "type": "stat",
   "description": "Inbound all failures",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_all_failures", "legendFormat": " " }
   ]
  },
  {
   "title": "unknown",
   "type": "stat",
   "description": "Inbound unknown trash",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_inbound_unknown", "legendFormat": " " }
   ]
  },
  { "title": "Outbound", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "outbound all successes",
   "type": "stat",
   "description": "Outbounds",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_outbound_all_successes", "legendFormat": " " }
   ]
  },
  {
   "title": "outbound all failures",
   "type": "stat",
   "description": "Outbounds",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_outbound_all_failures", "legendFormat": " " }
   ]
  },
  { "title": "vinternal_rtt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "getblocks",
   "type": "stat",
   "description": "internal_rtt",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_internal_rtt_getblocks", "legendFormat": " " }
   ]
  },
  {
   "title": "Get Memory Pool",
   "type": "stat",
   "description": "internal_rtt",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "aleo_internal_rtt_getmemorypool",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Get Peers",
   "type": "stat",
   "description": "internal_rtt",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_internal_rtt_getpeers", "legendFormat": " " }
   ]
  },
  {
   "title": "Get Sync",
   "type": "stat",
   "description": "internal_rtt",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "aleo_internal_rtt_getsync", "legendFormat": " " }
   ]
  },
  { "title": "misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Local Height",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_misc_block_height", "legendFormat": " " }
   ]
  },
  {
   "title": "MINED BLOCKS",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_misc_blocks_mined", "legendFormat": " " }
   ]
  },
  {
   "title": "duplicate blocks",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_misc_duplicate_blocks", "legendFormat": " " }
   ]
  },
  {
   "title": "duplicate sync blocks",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aleo_misc_duplicate_sync_blocks",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "orphan blocks",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_misc_orphan_blocks", "legendFormat": " " }
   ]
  },
  {
   "title": "rpc requests",
   "type": "stat",
   "description": "misc",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_misc_rpc_requests", "legendFormat": " " }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "inbound queues",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_inbound", "legendFormat": " " }
   ]
  },
  {
   "title": "outbound queues",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_outbound", "legendFormat": " " }
   ]
  },
  {
   "title": "queues consensus",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_consensus", "legendFormat": " " }
   ]
  },
  {
   "title": "queues peer events",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_peer_events", "legendFormat": " " }
   ]
  },
  {
   "title": "queues storage",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_storage", "legendFormat": " " }
   ]
  },
  {
   "title": "queues sync items",
   "type": "stat",
   "description": "Queues",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_queues_sync_items", "legendFormat": " " }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "all accepted",
   "type": "stat",
   "description": "Connections All Accepted",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_connections_all_accepted", "legendFormat": " " }
   ]
  },
  {
   "title": "All Initiated",
   "type": "stat",
   "description": "Connections All Initiated",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_connections_all_initiated", "legendFormat": " " }
   ]
  },
  {
   "title": "All Rejecrted",
   "type": "stat",
   "description": "Connections All Rejected",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aleo_connections_all_rejected", "legendFormat": " " }
   ]
  },
  {
   "title": "Connecting Peers",
   "type": "stat",
   "description": "Connections Connecting Peers",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aleo_connections_connecting_peers",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Connecting Peers Average Duration",
   "type": "stat",
   "description": "Connections Connecting Peers",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aleo_connections_average_duration",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "description": "Connections Connected Peers",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aleo_connections_connected_peers",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Disconnected Peers",
   "type": "stat",
   "description": "Connections Disconnected Peers",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aleo_connections_disconnected_peers",
     "legendFormat": " "
    }
   ]
  }
 ]
}